#!/usr/bin/env bash
# the server to send traffic to two web servers. The load balancing algorithm
# is round-robin.

sudo apt-get install -y haproxy

echo "ENABLED=1" >> /etc/default/haproxy
mv /etc/haproxy/haproxy.cfg{,.original}
touch /etc/haproxy/haproxy.cfg

printf %s "global
        log 127.0.0.1 local0 notice
        maxconn 200
        user haproxy
        group haproxy

defaults
        log     global
        mode    http
        option  httplog
        option  dontlognull
        retries 3
        option redispatch
        timeout connect 5000
        timeout client  30000
        timeout server  3000
        errorfile 400 /etc/haproxy/errors/400.http
        errorfile 403 /etc/haproxy/errors/403.http
        errorfile 408 /etc/haproxy/errors/408.http
        errorfile 500 /etc/haproxy/errors/500.http
        errorfile 502 /etc/haproxy/errors/502.http
        errorfile 503 /etc/haproxy/errors/503.http
        errorfile 504 /etc/haproxy/errors/504.http

frontend http-in
        timeout client  30000
        bind 0:80
        default_backend servers

backend servers
        timeout connect 3000
        timeout server  30000
        balance roundrobin
        server 87098-web-01 54.172.89.45: check
        server 87098-web-02 100.25.144.184:80 checki

" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
