#!/usr/bin/env bash
set -e

# This script installs and configures the HAproxy load balancer. It configures
# the server to send traffic to two web servers. The load balanceing algorithm
# is round-robin.
config="
frontend phine_frontend
    bind *:80
    mode http
    default_backend phine_backend
    timeout client 30s
    timeout connect 30s
    timeout server 30s

backend phine_backend
    balance roundrobin
    server 87098-web-01- web-01.phinehas.tech:80 check
    server 87098-web-02 web-02.phinehas.tech:80 check
    timeout server 30s
    timeout connect 30s
"

if [ $EUID -ne 0 ]; then
    echo "You must be root to run this script."
    exit 1
fi

function add_config() {
    # let's do some house checking first, ensure the configuration does not 
    # exist before we append to it
    if ! grep -q -e "phine_frontend" -e "phine_backend" /etc/haproxy/haproxy.cfg; then
        # configure HAproxy
        echo "$config" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null
    else
        echo "Configuration already exists."
        exit
    fi

    if ! grep -q "ENABLED" /etc/default/haproxy; then
        echo "ENABLED=1" | sudo tee -a /etc/default/haproxy > /dev/null
    fi

    # restart HAproxy
    sudo systemctl restart haproxy
}

# let's save time and check if the HAproxy package is already installed
if ! command -v haproxy > /dev/null; then
    # update package list
    sudo apt-get update -y

    # enable dedicated PPA for HAproxy 2.8
    if ! command -v add-apt-repository > /dev/null; then
        sudo apt-get install --no-install-recommends -y software-properties-common
    fi

    sudo add-apt-repository -y ppa:vbernat/haproxy-2.8

    # install HAproxy
    sudo apt-get install -y haproxy

    add_config
else
    # HAproxy is already installed, just add the configuration
    add_config
fi