#!/usr/bin/env bash

#Bash script that uses ssh to connect to my server using
#Private key ~/.ssh/school with the user ubuntu.

ssh -i ~/.ssh/school -o "PasswordAuthentication no" ubuntu@54.172.89.45
